version: '3.8'

services:
  webapp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - puppeteer

  puppeteer:
    image: mcr.microsoft.com/dotnet/sdk:7.0
