version: '3.7'

services:
  webapp:
    build:
      context: ../GeoBuyerParser
      dockerfile: Dockerfile
    container_name: geo-buyer-parser
    ports:
      - "8081:8080"
    networks:
      - appnetwork

networks:
  appnetwork:
    driver: nat
